### ISSUE TITLE
User can create a new trip

### ISSUE THREAD

**Issue by sertmer** [sertmer/GlobeTrotter#10]
```
As a logged in user
When I fill out all of the forms on the create trip page
I want to click submit
So that I can create a new trip
```

Subtasks:
- [ ] error handling to ensure all forms are filled out, dates selected, everything in correct format
- [x] pull things out of local state, wrap in correct object format for POST request
- [x] fire POST on submit

Acceptance Criteria:
- [x] All tests passing
- [x] Happy path tested
- [x] Sad path(s) tested
    - [x] Sad path #1
- [ ] Documentation is written

**Comment by Dunn-Austen** [comment]
Includes the following sub-issues:
- #4 
- #11 

I've referenced those issues here and pulled them off the Project Board for de-cluttering purposes

**Comment by Dunn-Austen** [comment]
Error handling has been migrated to a new issue
