### ISSUE TITLE
User see all trip information on the TripPreview view

### ISSUE THREAD

**Issue by sertmer** [sertmer/GlobeTrotter#27]
```
As a logged in user
When I click on an individual trip
I want view all of that trips information in one place
So that I can quickly review my plans
```

Subtasks:
- [x] Style Trip Preview to display the information nicely

Acceptance Criteria:
- [x] All tests passing
- [ ] Happy path tested
- [ ] Sad path(s) tested
    - [ ] Sad path #1
    - [ ] Sad path #2
- [ ] Documentation is written

**Comment by Dunn-Austen** [comment]
References Issue #24
