### ISSUE TITLE
User can navigate to the locations view

### ISSUE THREAD

**Issue by sertmer** [sertmer/GlobeTrotter#29]
```
As a logged in user
When view a specific Trip, 
I want to be taken to the Locations view
So that I can see a map of that location, and a calendar of my events
```

Subtasks:
- [x] implement Navigation on press of location
- [ ] Build out location, calendar, and day components

Acceptance Criteria:
- [ ] All tests passing
- [ ] Happy path tested
- [ ] Sad path(s) tested
    - [ ] Sad path #1
    - [ ] Sad path #2
- [ ] Documentation is written

**Comment by Dunn-Austen** [comment]
We currently have the map rendering, and are working on getting the functionality for generating (20) markers based off of the fetched yelp data.
