### ISSUE TITLE
User can add start / end dates to a new trip via a calendar

### ISSUE THREAD

**Issue by sertmer** [sertmer/GlobeTrotter#7]
```
As a logged in user
When I view the create trip page
I want to add start and end dates for that desination
So that I can plan my trip
```

Subtasks:
- [ ] add two calendars with a library (?)
- [x] capture all the dates, store in local state on submit

Acceptance Criteria:
- [ ] All tests passing
- [ ] Happy path tested
- [ ] Sad path(s) tested
    - [ ] Sad path #1
    - [ ] Sad path #2
- [ ] Documentation is written

**Comment by Dunn-Austen** [comment]
Resolved by the last round of PRs
